$: << File.dirname(__FILE__)

require 'rubygems'
require 'oauth'
require 'json'
require 'time'
require 'xmlsimple'

require 'trip_it/util/param_util'

require 'trip_it/base'
require 'trip_it/oauth'

require 'trip_it/classes/tp_date_time'
require 'trip_it/classes/profile'
require 'trip_it/classes/profile_email_address'
require 'trip_it/classes/group'
require 'trip_it/classes/image'
require 'trip_it/classes/flight_status'
require 'trip_it/classes/trip'
require 'trip_it/classes/trip_crs_remark'
require 'trip_it/classes/invitee'
require 'trip_it/classes/traveler'
require 'trip_it/classes/address'
require 'trip_it/classes/points_program'
require 'trip_it/classes/points_program_activity'
require 'trip_it/classes/points_program_expiration'
require 'trip_it/classes/objects/base_object'
require 'trip_it/classes/objects/reservation_object'
require 'trip_it/classes/objects/activity_object'
require 'trip_it/classes/objects/air_object'
require 'trip_it/classes/objects/car_object'
require 'trip_it/classes/objects/cruise_object'
require 'trip_it/classes/objects/directions_object'
require 'trip_it/classes/objects/lodging_object'
require 'trip_it/classes/objects/map_object'
require 'trip_it/classes/objects/note_object'
require 'trip_it/classes/objects/rail_object'
require 'trip_it/classes/objects/restaurant_object'
require 'trip_it/classes/objects/transport_object'
require 'trip_it/classes/objects/weather_object'

require 'trip_it/classes/segments/air_segment'
require 'trip_it/classes/segments/cruise_segment'
require 'trip_it/classes/segments/rail_segment'
require 'trip_it/classes/segments/transport_segment'